config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  end

  scope module: :web do
    root 'tasks#index'

    resources :users, except: [:index, :new] do
      scope module: :users do
        resources :tasks, only: [:index]
      end
    end
    get :signup, to: 'users#new', as: :signup

    get :login, to: 'sessions#new', as: :login
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy', as: :logout

    resources :tasks do
      member do
        patch :next_state
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :role

  has_many :tasks,
    inverse_of: :user,
    dependent: :destroy

  has_many :assigned_tasks,
    class_name: 'Task',
    inverse_of: :assignee,
    foreign_key: :assignee_id

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    email: true

  validates :name,
    presence: true,
    length: { within: 3..30 }

  validates :password,
    length: { within: 4..20 },
    allow_blank: :true

  before_create :generate_auth_token

  class << self
    def new_token(column)
      begin
        token = SecureRandom.urlsafe_base64
      end while User.exists?(column => token)
      token
    end
  end

  def has_role?(role_name)
    role.present? && role.name == role_name.to_s
  end

  # def admin?
  Role::NAMES.each do |role_name|
    define_method "#{role_name}?" do
      has_role? role_name
    end
  end

  def associated_tasks
    Task.where 'user_id = :user_id OR assignee_id = :user_id', user_id: id
  end

  private

  def generate_auth_token
    self.auth_token = self.class.new_token :auth_token
  end
    
end

app/controllers/web/users/base_controller.rb
module Web
  module Users
    class BaseController < Web::BaseController

      helper_method :resource_user

      protected

      def resource_user
        @resource_user ||= User.find params[:user_id]
      end

    end
  end
end

app/controllers/web/users/tasks_controller.rb
module Web
  module Users
    class TasksController < Web::Users::BaseController

      helper_method :resource_collection

      def index; end

      private

      def resource_collection
        return @resource_collection if @resource_collection
        @resource_collection = if current_user && current_user.admin? && current_user == resource_user 
          Task.all
        else
          resource_user.associated_tasks
        end
        @resource_collection = @resource_collection.ordered.page(params[:page]).per(20)
      end

    end
  end
end

app/controllers/web/users_controller.rb
module Web
  class UsersController < BaseController
    helper_method :resource_user

    before_filter :require_no_user, only: [:new, :create]

    def show
      authorize resource_user, :show?
    end

    def new
      authorize :user, :create?
    end

    def create
      authorize :user, :create?

      resource_user.assign_attributes resource_user_params
      if resource_user.save
        login resource_user
        flash[:success] = t '.success'
        redirect_to user_tasks_url(resource_user)
      else
        render :new
      end
    end

    def edit
      authorize resource_user, :update?
    end

    def update
      authorize resource_user, :update?

      if resource_user.update_attributes resource_user_params
        flash[:success] = t '.success'
        redirect_to resource_user
      else
        render :edit
      end
    end

    def destroy
      authorize resource_user, :destroy?

      resource_user.destroy
      flash[:success] = t '.success'
      redirect_to root_url
    end

    private

    def resource_user
      @user ||= if params[:id].present?
        User.find params[:id]
      else
        User.new
      end
    end

    def resource_user_params
      params.has_key?(:user) ? params.require(:user).permit(policy(resource_user).permitted_attributes) : {}
    end
  end
end

app/helpers/web/users_helper.rb
module Web
  module UsersHelper
    def roles_collection_for_select
      Role.all
    end
  end
end

app/views/web/users/_tabs.html.haml
%ul.nav.nav-tabs
  %li{class: ('active' if active == :users)}
    = link_to t('.profile'), resource_user
  %li{class: ('active' if active == :tasks)}
    = link_to t('.tasks'), user_tasks_path(resource_user)

app/views/web/users/edit.html.haml
%h1= resource_user.name

= render 'tabs', active: :users

.row
  .col-lg-4.col-md-5.col-sm-6
    = simple_form_for resource_user do |f|
      = f.input :name
      = f.input :email
      = f.input :password
      = f.input :password_confirmation
      - if policy(resource_user).permitted_attributes.include?(:role_id)
        = f.input :role_id, collection: roles_collection_for_select, include_blank: 'user'
      = link_to t('.cancel'), resource_user, class: 'btn btn-default'
      = f.button :submit, t('.submit'), class: 'btn-primary'

app/views/web/users/new.html.haml
%h1= t '.title'

.row
  .col-lg-4.col-md-5.col-sm-6
    = simple_form_for resource_user do |f|
      = f.input :name
      = f.input :email
      = f.input :password, required: true
      = f.input :password_confirmation, required: true
      = f.button :submit, t('.submit'), class: 'btn-primary'

app/views/web/users/show.html.haml
%h1= resource_user.name

= render 'tabs', active: :users

.text-right
  - if policy(resource_user).update?
    = link_to t('.edit'), [:edit, resource_user], class: 'btn btn-default'
  - if policy(resource_user).destroy?
    = link_to t('.destroy'), resource_user, method: :delete, data: { confirm: t('.destroy_confirm') }, class: 'btn btn-danger'

%dl
  %dt= t '.email'
  %dd= mail_to resource_user.email
  %dt= t '.role'
  %dd= t "roles.#{resource_user.role.try(:name) || 'user'}"