config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  end

  scope module: :web do
    root 'tasks#index'

    resources :users, except: [:index, :new] do
      scope module: :users do
        resources :tasks, only: [:index]
      end
    end
    get :signup, to: 'users#new', as: :signup

    get :login, to: 'sessions#new', as: :login
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy', as: :logout

    resources :tasks do
      member do
        patch :next_state
      end
    end
  end
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController; end
end

app/controllers/web/base_controller.rb
module Web
  class BaseController < ApplicationController
    protect_from_forgery with: :exception

    layout 'web/layouts/application'

    rescue_from Pundit::NotAuthorizedError, with: :unauthorized

    helper_method :current_user

    def current_user
      return nil if cookies[:auth_token].blank?
      @current_user ||= User.find_by auth_token: cookies[:auth_token]
    end

    protected

    def login(user, remember = false)
      if remember
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
    end

    def logout
      cookies.delete :auth_token
    end

    def unauthorized
      flash[:error] = t :unauthorized
      redirect_to current_user || login_url
    end

    def require_no_user
      if current_user
        return redirect_to root_url
      end
    end
  end
end

app/controllers/web/users/base_controller.rb
module Web
  module Users
    class BaseController < Web::BaseController

      helper_method :resource_user

      protected

      def resource_user
        @resource_user ||= User.find params[:user_id]
      end

    end
  end
end

app/views/web/base/_flash_messages.html.haml
- { success: :success, error: :danger }.each do |key, css_class|
  - if flash[key].present?
    .alert.alert-dismissable{class: "alert-#{css_class}", role: 'alert'}
      .container
        %button.close{type: 'button', data: {dismiss: 'alert'}}
          %span &times
        = flash[key]

app/views/web/base/_main_menu.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to 'TM', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li{class: ('active' if respond_to?(:resource_user) && resource_user == current_user)}
          = link_to current_user.name, current_user
        %li
          = link_to t('.logout'), logout_path, method: :delete
      - else
        %li{class: ('active' if controller_name == 'users')}
          = link_to t('.signup'), signup_path
        %li{class: ('active' if controller_name == 'sessions')}
          = link_to t('.login'), login_path

app/views/web/base/_task.html.haml
%tr.tasks-item{id: "tasks-item-#{task.id}"}
  %td= task.id
  %td
    = link_to task.name, task
    = task_state_label task
    .tasks-item__author
      = "#{t '.user'}:"
      = link_to task.user.name, task.user
  %td= l task.created_at, format: '%d.%m.%Y - %H:%M'
  %td
    - if task.assignee.present?
      = link_to task.assignee.name, task.assignee
    - else
      = t '.assignee_blank'
  %td
    - if policy(task).next_state?
      = task_next_state_button task, data: { remote: true, disable_with: t('statuses.processing') }, class: 'btn-block btn-sm'
  %td.text-center
    - if policy(task).update?
      = link_to edit_task_path(task), title: t('.edit_title'), class: 'btn btn-link btn-sm' do
        %span.glyphicon.glyphicon-pencil
    - if policy(task).destroy?
      = link_to task, method: :delete, data: { remote: true, confirm: t('.destroy_confirm') }, title: t('.destroy_title'), class: 'btn btn-link btn-sm' do
        %span.glyphicon.glyphicon-remove.text-danger

app/views/web/base/_tasks.html.haml
.tasks
  - if tasks.present?
    %table.table.table-striped
      %colgroup
        %col{style: 'width: 5%'}
        %col{style: 'width: 40%'}
        %col{style: 'width: 15%'}
        %col{style: 'width: 15%'}
        %col{style: 'width: 15%'}
        %col{style: 'width: 10%'}
      %thead
        %tr
          %th= t '.id'
          %th= t '.details'
          %th= t '.created_at'
          %th= t '.assignee'
          %th
          %th
      %tbody
        = render partial: 'web/base/task', collection: tasks, as: :task

    = paginate tasks, theme: 'twitter-bootstrap-3'
  - else
    .tasks__empty= t '.empty'